spring:
  application:
    name: eureka-customer
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka/
server:
  port: 9000
# active feign
feign:
  hystrix:
    enabled: true